name: 532-project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - dash
  - dash-bootstrap-components
  - plotly
  - dash-core-components
  - dash-html-components